### ISSUE TITLE
AttributeError: 'Dataset' object has no attribute 'value'

### ISSUE THREAD

**Issue by paula-rj** [dennissergeev/cloudsat_polarlows#1]
Hi! 

I'm trying to open a Cloudsat file. I've been able to install the environment and run some code of the "Quickstart" notebook, but when I want to run In[23]:

`cloudsat_lons, cloudsat_lats, cloudsat_height, cloudsat_time, elev = get_geodata(fname, return_list=True)
elev = elev * 1e-3`

it throws the following error:

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-23-06c61deaff80> in <module>
----> 1 cloudsat_lons, cloudsat_lats, cloudsat_height, cloudsat_time, elev = get_geodata(fname, return_list=True)
      2 elev = elev * 1e-3

~/cloudsat_polarlows/cloudsat_read.py in get_geodata(h5name, varnames, proftime2datetime, return_list)
     22 
     23         var_dict = {}
---> 24         for ivar in varnames:
     25             fld_dtype = f[topkey]['Geolocation Fields'][ivar].value[0][0].dtype
     26             var_dict[ivar] = (f[topkey]['Geolocation Fields'][ivar].value.sastype(fld_dtype))

AttributeError: 'Dataset' object has no attribute 'value'

I don't know why this happends, I haven't modified the *cloudsat_read.py* script.
 I'll be very thankfull if you could help me.

**Comment by dennissergeev** [comment]
Hi @paula-rj 

This error is caused by the `h5py` library deprecating the `value` property of `Dataset`. I have updated the `cloudsat_read` module now (and the `environment.yml` file). So if you git-pull the changes and (optionally) update your conda environment, it should work.

**Comment by paula-rj** [comment]
Thanks! Now it works
